### ISSUE TITLE
external links to GWAS QTLs at soybase are broken

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/intermine-soymine#13]
maybe instead of the form:
https://soybase.org/sbt/search/search_results.php?category=QTLName&search_term=Seed%20weight%202-g3
you're going to have to settle for the more generic:
https://soybase.org/GWAS/index.php?gwasfamily=Seed%20weight%202

? at least, that was the most sensible place I could find when I tried the search for 
Seed weight 2-g3 at the soybase home page search box...

**Comment by adf-ncgr** [comment]
David Grant gave his blessing to what I had suggested above, namely:
https://soybase.org/GWAS/index.php?gwasfamily=Seed%20weight%202
will fwd you the email exchange for reference, but I think that is basically as good as it's getting for now.

**Comment by sammyjava** [comment]
I simply removed the link for now since it isn't a one-to-one correspondence.
