### ISSUE TITLE
improve comparison template

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/intermine-soymine#14]
initial criticism of "Soybean Gene Family Partners" from @sammyjava 

> Please use the syntax that I've established (mine standard): Gene Family --> Soybean Gene Pairs (--> gives you that nice arrow). And a description that starts with "find" or such, keeping the main query description short and simply describing the query (I know, that's hard):
> 
> "Find pairs of soybean genes in the same gene family. Default: defense response. (The LIS mines use gene family membership to define homologous genes.)"
> 
> (I can edit them directly in the userprofile database, but can't using the UI.)
> 
> Also, your query returns 10,760 rows - way too many for a default. Use "defense response to fungus".
> 
> Finally, this is an awkward example because you're returning _pairs_ of genes, and we cannot make a list of pairs or do anything with it if we could. So there isn't much we can do with those pairs other then dump them into a spreadsheet. Ponder further use of your examples - what's the next step one does with the results of the query? Also, this query results in duplicate pairs, of course, nothing we can do about that.

**Comment by sammyjava** [comment]
We're good on SoyMine templates now, at least up to those that we planned.
