### ISSUE TITLE
templates tagged with appropriate im:aspect:* tags not showing up in home page tabs

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/intermine-soymine#16]
as it was with im:aspect:comparison and the much maligned Gene Family --> Soybean Gene Pairs 
so it is with im:aspect:genomics and the inoffensive but ill-fated Gene --> Proteins (copied with only slight mutation from medicmine, so it must be good). It has im:public and appears as it should on the Templates page for anonymous users. It just doesn't get a place in the spotlight. My career as an aspiring templateer is being nipped in the bud! But it can wait until you're back...

**Comment by sammyjava** [comment]
Closing, since this is a core IM bug.
