### ISSUE TITLE
TO terms have lost their names

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/intermine-soymine#20]
making the template query TO Term  ==>  QTLs pretty uninspiring.

**Comment by sammyjava** [comment]
Merge issue. The QTL-TO associations came in as unnamed duplicate TOs with the same ID.  Shoulda merged on ID.
![screenshot_2018-10-22 soymine query results page](https://user-images.githubusercontent.com/5657219/47322987-40874980-d617-11e8-89fc-020a4093faf7.png)

**Comment by sammyjava** [comment]
Will rebuild, but it'll take a while.

**Comment by sammyjava** [comment]
Fixed and in production.
