### ISSUE TITLE
GWAS displayer: less clutter, mo' betta

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/intermine-soymine#21]
The labels on SNPs in the GWAS display tends to generate a lot of clutter, at least when fully zoomed out. My preference would be to display the SNP identity on a mouseover, and color code them to indicate which trait association is being asserted (with a legend). Open to other thoughts, the above is more or less copped from the way ZBrowse does things.

**Comment by sammyjava** [comment]
I think the goal of this old enhancement has been implemented. Or, if not, post up a new issue about the current GWAS displayer.

**Comment by adf-ncgr** [comment]
For the record, I don't think it has been implemented, but it looks like there's s decent chance that a summer of code intern may produce a GWAS displayer as part of the dataviz proposal, so I think we can probably hold off on further efforts in this direction and see what comes out of that.

**Comment by sammyjava** [comment]
Or mark up a graphical example so I understand what you want. I think it looks pretty darned good right now with the rollovers.

**Comment by sammyjava** [comment]
Keep in mind this is re. the linear displayer. I do have a circular version on the back bench.

**Comment by adf-ncgr** [comment]
yes the linear displayer; rollovers are good, but results names still collide:
![image](https://user-images.githubusercontent.com/2009605/79891520-51f11380-83be-11ea-8549-7fcf8aa9960d.png)

I was imagining something like this:
![image](https://user-images.githubusercontent.com/2009605/79891797-b9a75e80-83be-11ea-8d4d-91bb156816ac.png)

(aren;t you impressed at how quickly I mocked that up!)

**Comment by sammyjava** [comment]
Oh right, colors to phenotypes, then rollover to see what's there. Forgot about that. I'll poke at it at some point. There may be stuff that's not supported by CanvasXpress Scatter2D, dunno.

**Comment by adf-ncgr** [comment]
This suggests it could be done:
https://github.com/neuhausi/canvasXpress/issues/61#issuecomment-480417789

though I didn't really grok his data structure.

**Comment by sammyjava** [comment]
Sorta moved to mine-issues but I'll refer to this closed issue to see what it's about since it's long.
