### ISSUE TITLE
GWAS experiment has no displayer

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/intermine-soymine#22]
https://mines.legumeinfo.org//soymine/portal.do?class=GWASExperiment&externalids=KGK20170712.1

Seems like the associated SNPs have genomic locations, e.g.:
https://mines.legumeinfo.org//soymine/portal.do?class=QTL&externalids=Seed+yield+3-g6

so not sure why the graphic wouldn't show up. Maybe there's a good reason.

**Comment by sammyjava** [comment]
Take a look at the p-values.

**Comment by adf-ncgr** [comment]
that's a pretty good reason. however, now that I'm looking I remember something that had come up when we were dealing with the soybase GWAS data in the context of ZBrowse. Some of the soybase GWAS QTLs don't have p-values calculated, but have "R2 values" instead, e.g.:
https://www.soybase.org/GWAS/index.php?gwasfamily=Seed+yield+3

to make matters still more complicated, some have both:
https://www.soybase.org/GWAS/index.php?gwasfamily=Seed%20oil%206

I'm not sure what the best way to handle this is, but it seems like at a minimum it would be good to be able to see the genomic distributions, if not also some y-axis representation of the relative significance. Reopening, but we might not want to do anything until we can get the opinion of a qualified expert.

**Comment by sammyjava** [comment]
What this displayer does is plot -log10(p) of QTL/markers against chromosomes, where the p value is supplied by SoyBase. That's what it does, with the p values supplied by SoyBase. If they're not supplied, we don't have a plot.
