### ISSUE TITLE
link to genotype study proudly displayed on home page gives no result

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/intermine-soymine#24]
Clicking "Click here to see the US Germplasm genotyping study, added in v0.10. Let us know how you'd like us to improve the genotype matrix viewer!" 
yields a non-result. I'd like you to improve the genotype matrix viewer by making it display something ;)

**Comment by adf-ncgr** [comment]
https://mines.legumeinfo.org/soymine/report.do?id=850561699 appears to be where the action should be, although obviously it would be better to have a stable URL to avoid recurrence and when I click the share option it gives me https://mines.legumeinfo.org/soyminenull which doesn't seem FAIR.

**Comment by adf-ncgr** [comment]
seems like https://mines.legumeinfo.org/soymine/portal.do?class=GenotypingStudy&externalids=BARC_1059007 should work, but doesn't

**Comment by adf-ncgr** [comment]
NB: the reason I have a bee in my bonnet is that I was thinking I might link to this in the PeanutBase proposal as an example of handling genotype data in the mines.

**Comment by sammyjava** [comment]
Fixed. Forgot to add GenotypingMatrix.primaryIdentifier to dbmodel/resources/class_keys.properties :^/
