### ISSUE TITLE
should ontology relationships include "transitive closure" derived relationships?

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/intermine-soymine#7]
this is not soymine-specific, so feel free to re-home as appropriate. The idea is that there is currently no way that I can see of querying using ontological relations in a way that does not assume you know the structure of the ontology in detail. For example, if I actually wanted to get all QTLs that were derived from "plant phenological traits" I would have to construct a rather elaborate query that included the possibility that the QTL was tagged directly with TO:0000933 but could also be tagged with an "is_a" child of that term or an "is_a-is_a" grandchild, etc. 

As I understand it, chado has a cvterm_path table that is computed (though perhaps not with absolute semantic rigor) from the cvterm_relationships stored there. Leveraging this or doing something analogous as a post-processing step in the mines might be worth some consideration.

**Comment by ekcannon** [comment]
The Tripal module ontology_search does this sort of searching, taking advantage of the table cvtermpath. It needs to be re-written to improve the code and the API, and to make it more GP so that it can be used by non-Tripal code. But it requires that ontologies be represented in the Chado schema.

This issue should be moved to LegumeFederation/Traits.

**Comment by adf-ncgr** [comment]
@ekcannon- I was actually seeing this as more of an issue with respect to intermine's handling of ontologies in general; has a trait-ontology connection for sure, but I'm not seeing that as a reason for it to belong in the Traits group (unless perhaps the Traits group wants to be morphed into an Ontology group). I was curious however when poking into the legumeinfo chado that I couldn't seem to find the TO terms that I was using in my example. That might be an issue for the Traits group!

**Comment by sammyjava** [comment]
NO.
