### ISSUE TITLE
List of genetic markers- broken or simply underwhelming?

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/intermine-soymine#8]
starting with this query inspired from Ethy's BIC poster:
https://mines.legumeinfo.org/soymine/keywordSearchResults.do?searchTerm=E1+OR+E2+OR+E3+OR+E4+OR+E5+OR+E6+OR+E7+OR+E8+OR+E9+OR+Dt1+OR+Dt2+OR+J&searchBag=&facet_Category=GeneticMarker

then Create a list from the results. Not much love on the resultant page; seems like at least the
little table ought to have rows...

**Comment by sammyjava** [comment]
Yeah, that's the annoying feature of list analysis pages, that if you have missing data, the whole table breaks. Those markers aren't on chromosomes so the table breaks. It won't allow nulls. Vivek and I have talked about it - I had to jimmy the page to handle genes not being on supercontigs/chromosomes.

We'll keep this issue alive, as I think there are some workarounds. Not much to look at on a list analysis page for non-genomic markers, anyway, but at least they shouldn't break the page.

**Comment by sammyjava** [comment]
This is a general InterMine bug, but SoyMine is a perfectly good place to remind us of it. One of many bugs in IM because the IMers in Cambridge only think of genomics, and everything is on a chromosome, not even a scaffold. Terribly limiting outlook.

**Comment by adf-ncgr** [comment]
well, I wasn't going to say anything about the genetics/genomics divide but since you brought it up, one might make the argument that genetic markers are like QTLs- sure to be defined genetically, only sometimes defined genomically; this would perhaps suggest (though I am not sure I believe this) the columns for these should give their linkage groups assignments. I see the QTL list results only gives the one column for DB identifier. probably not worth a lot of kerfuffle but might be instructive to review sometime what we all think the "important" things to include as columns for a results list are for each of our "major" types.

**Comment by sammyjava** [comment]
I agree, but right now that would break anything that is NOT on a linkage group. The list analysis is horribly hard-coded to deal only with chromosomal features. So that's down the line from making the list analysis more accommodating.

**Comment by adf-ncgr** [comment]
are you saying that currently defining the columns presented in lists are a subtractive procedure, 
starting with the set that makes sense for genomic features and then removing everything that doesn't make sense for the type in question (e.g. everything but DB Identifier for the QTLs)?
horrible indeed if true!

**Comment by sammyjava** [comment]
Um, yeah. I think so. It sucks, however you describe it.

**Comment by sammyjava** [comment]
Closing this, I don't think any action is called for on my part. And it may have been fixed in the core for all I know. :)
